<?php

return array (
    'key' => '54de1384f46ce',
    'name' => 'columns',
    'label' => 'Columns',
    'display' => 'row',
    'sub_fields' => array (
        array (
            'key' => 'field_59d343f91741f',
            'label' => 'Content',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_54de1389f46cf',
            'label' => 'Columns',
            'name' => 'columns',
            'type' => 'repeater',
            'value' => NULL,
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 1,
            'max' => 4,
            'layout' => 'block',
            'button_label' => 'Add Column',
            'sub_fields' => array (
                array (
                    'key' => 'field_54de1392f46d0',
                    'label' => 'Content',
                    'name' => 'column',
                    'type' => 'wysiwyg',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
            ),
        ),
        array (
            'key' => 'field_59d3440317420',
            'label' => 'Settings',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array (
            'key' => 'field_59d35b69d0d97',
            'label' => 'Content Horizontal Alignment',
            'name' => 'horizontal_alignment',
            'type' => 'select',
            'value' => NULL,
            'instructions' => 'This should be used when only 1 column is used, else will not take effect. It will center align the content container, but not the content itself, as that styling can be done in the wysiwyg editor upon context.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '33.333333',
                'class' => '',
                'id' => '',
            ),
            'choices' => array (
                'h-left' => 'Left',
                'h-center' => 'Center',
            ),
            'default_value' => array (
                0 => 'h-left',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
    ),
    'min' => '',
    'max' => '',
);
